2025-03-06 20:59:29 | ERROR | Ошибка при проверке отложенных постов: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
Traceback (most recent call last):

  File "C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py", line 1467, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x0000019AD07939C0>
    │       └ <function run at 0x0000019AC4DB5EE0>
    └ <module 'asyncio' from 'C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\asyncio\\__init__.py'>

  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x0000019AD0306080>
           │      └ <function Runner.run at 0x0000019AC708EB60>
           └ <asyncio.runners.Runner object at 0x0000019AD075E270>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py:1459> wait_for=...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000019AC708C720>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000019AD075E270>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 708, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x0000019AC708C680>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 679, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000019AC708E480>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2027, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000019AC6FB5440>
    └ <Handle Task.task_wakeup()>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup()>

> File "C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\bot.py", line 1192, in check_scheduled_posts
    posts = await Database.get_pending_posts()
                  │        └ <staticmethod(<function Database.get_pending_posts at 0x0000019ACF5A4900>)>
                  └ <class 'database.models.Database'>

  File "C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\database\models.py", line 271, in get_pending_posts
    data = await Database._read_json(POSTS_FILE)
                 │        │          └ WindowsPath('C:/Users/Asus/OneDrive/Рабочий стол/Kwork/chencnik/database/posts.json')
                 │        └ <staticmethod(<function Database._read_json at 0x0000019ACF593D80>)>
                 └ <class 'database.models.Database'>

  File "C:\Users\Asus\OneDrive\Рабочий стол\Kwork\chencnik\database\models.py", line 53, in _read_json
    return json.loads(content)
           │    │     └ '\ufeff{"posts": []}\n'
           │    └ <function loads at 0x0000019AC7E59620>
           └ <module 'json' from 'C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\json\\__init__.py'>

  File "C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
